#ifndef _GUI_CONSTANTS_
#define _GUI_CONSTANTS_

const int SCREEN_WIDTH = 1000;
const int SCREEN_HEIGHT = 750;

const int FILE_LIST_LEFT_PADDING = 50;
const int FILE_LIST_RIGHT_PADDING = 50;
const int FILE_LIST_TOP_PADDING = 100;
const int FILE_LIST_BOTTOM_PADDING = 75;
const int FILE_ICON_SIZE = 20;
const int FILE_SPACING = 0;

const int CHAR_WIDTH = 10;
const int FILE_TEXT_ICON_GAP = 10;
const int FILE_TEXT_HEIGHT = 15;
const int TEXT_TOP_OFFSET = 5;

const int CURRENT_DIRECTORY_BAR_HEIGHT = 20;
const int CURRENT_DIRECTORY_TOP_PADDING = 20;

#endif
